name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t streamlit-app:latest .
      - name: Deploy to EC2
        env:
          DEPLOY_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          DEPLOY_HOST: ${{ secrets.EC2_HOST }}
          DEPLOY_USER: ${{ secrets.EC2_USER }}
          REPO_URL: https://github.com/AnjaliShukla2309/Practise.git
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
        
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST << EOF
            mkdir -p ~/app
            cd ~/app
            rm -rf *
            rm -rf .*
            git clone $REPO_URL .
            docker build -t streamlit-app:latest .
            docker rm -f streamlit-container || true
            docker run -d -p 80:8501 --name streamlit-container streamlit-app:latest
          EOF

